In [ ]:

PANDAS
1.Pandas is a Python library used for working with data sets.
2.It has the functions for analyzing, cleaning, exploring and manipulating data.

pandas installation

In [ ]:
pip install pandas

In [5]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/soujanyamutapuram/.local/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: tzdata>=2022.7 in /home/soujanyamutapuram/.local/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/soujanyamutapuram/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.22.4 in /home/soujanyamutapuram/.local/lib/python3.10/site-packages (from pandas) (2.2.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

Importing pandas

In [2]:
import pandas as pd

pandas version

In [4]:
print(pd.__version__)

2.2.3

Installing Specific version 
#pip install pandas= 1.4.2

Types of pandas data structures are :
1.Series 2.Data Frames 3.Panel
Series : one D array with any data type.

In [8]:
#creating a series with default integer index
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
#Creating a Series with custom index labels
S1 = pd.Series([10,20,30,40], index=['a','b','c','d'])
print(S1)

a    10
b    20
c    30
d    40
dtype: int64

In [18]:
S1['c']

np.int64(30)

In [19]:
s[2]

np.int64(30)

In [21]:
# using list 
ls=[10,20,30,40]
pd.Series(ls)

0    10
1    20
2    30
3    40
dtype: int64

In [22]:
pd.Series(ls,index =["i","ii","iii","iv"])

i      10
ii     20
iii    30
iv     40
dtype: int64

Data Frames
pandas dataframes is a 2 dimensional data structure
similar to 2 dimensional array
Table with rows and columns

In [23]:
# Creating a Dataframe
mydataset={"cars":['bmw','volvo','ford'],'passing' :[3,7,2]}
myvar=pd.DataFrame(mydataset)

In [24]:
myvar

    cars  passing
0    bmw        3
1  volvo        7
2   ford        2

In [15]:
print(myvar.cars[0])

bmw

In [25]:
# creating another data frame 
data = {"Name" :['soujanya','Santhosh','Hithesh'],
        "Age":[34,30,25],
        "City":['Delhi','Hyderabad','Kerala']
        }
df=pd.DataFrame(data)

In [26]:
df

       Name  Age       City
0  soujanya   34      Delhi
1  Santhosh   30  Hyderabad
2   Hithesh   25     Kerala

In [27]:
#Filtering data
print(df[df['Age']>25])

       Name  Age       City
0  soujanya   34      Delhi
1  Santhosh   30  Hyderabad

In [28]:
#Adding a new column
df['salary'] = [50000,80000,40000]

In [29]:
df

       Name  Age       City  salary
0  soujanya   34      Delhi   50000
1  Santhosh   30  Hyderabad   80000
2   Hithesh   25     Kerala   40000

In [30]:
#summary
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
 3   salary  3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 224.0+ bytes
None

In [8]:
#Adding a new column with some Operations
import pandas as pd
dic={'items':['pen','pencil','book','A4 paper','toy','fan','light'],
     'cost':[10,20,50,60,30,2000,500],
     'quantity':[10,34,20,15,16,5,1]
     }
df2=pd.DataFrame(dic)
df2

      items  cost  quantity
0       pen    10        10
1    pencil    20        34
2      book    50        20
3  A4 paper    60        15
4       toy    30        16
5       fan  2000         5
6     light   500         1

In [11]:
#df2['Totalprice']=df2['cost']*df2['quantity']
df2['cost']*df2['quantity']

0      100
1      680
2     1000
3      900
4      480
5    10000
6      500
dtype: int64

In [12]:
df2

      items  cost  quantity
0       pen    10        10
1    pencil    20        34
2      book    50        20
3  A4 paper    60        15
4       toy    30        16
5       fan  2000         5
6     light   500         1

In [19]:
df2['Totalprice']=df2['cost']*df2['quantity']
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [20]:
# Selecting and Slicing
#iloc and loc
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [21]:
df2.iloc[2]

items         book
cost            50
quantity        20
Totalprice    1000
Name: 2, dtype: object

In [22]:
df2.iloc[[2,3,4]]

      items  cost  quantity  Totalprice
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480

In [25]:
df2.loc[[1,4],['items','Totalprice']]

    items  Totalprice
1  pencil         680
4     toy         480

In [28]:
df2.loc[[1,4],['cost','Totalprice']]

   cost  Totalprice
1    20         680
4    30         480

In [30]:
df2.loc[4,'items']

'toy'

In [32]:
# Analysis
df3=df2.copy()
df3

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [33]:
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [34]:
df3.columns

Index(['items', 'cost', 'quantity', 'Totalprice'], dtype='object')

In [35]:
df3.head()

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480

In [36]:
df3.tail()

      items  cost  quantity  Totalprice
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [37]:
df3.tail(1)

   items  cost  quantity  Totalprice
6  light   500         1         500

In [38]:
df3.head(1)

  items  cost  quantity  Totalprice
0   pen    10        10         100

In [39]:
df3.head(2)

    items  cost  quantity  Totalprice
0     pen    10        10         100
1  pencil    20        34         680

In [ ]:
#changing values

In [40]:
df3

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [42]:
df3.iloc[2,2]=50

In [53]:
df3.iloc[2,3]

np.float64(1000.0)

In [45]:
import numpy as np

In [49]:
#df3.iloc[5,3]=np.nan

In [52]:
df3

      items  cost  quantity  Totalprice
0       pen    10        10       100.0
1    pencil    20        34       680.0
2      book    50        50      1000.0
3  A4 paper    60        15       900.0
4       toy    30        16       480.0
5       fan  2000         5         NaN
6     light   500         1       500.0

In [54]:
df3.iloc[3,1]

np.int64(60)

In [55]:
df3.iloc[3,1]=np.nan

In [56]:
df3

      items    cost  quantity  Totalprice
0       pen    10.0        10       100.0
1    pencil    20.0        34       680.0
2      book    50.0        50      1000.0
3  A4 paper     NaN        15       900.0
4       toy    30.0        16       480.0
5       fan  2000.0         5         NaN
6     light   500.0         1       500.0

In [57]:
df3.iloc[6,2]='10'

/tmp/ipykernel_5229/3746136714.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '10' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df3.iloc[6,2]='10'

In [58]:
df3

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
3  A4 paper     NaN       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5         NaN
6     light   500.0       10       500.0

In [59]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   items       7 non-null      object
 1   cost        6 non-null      float64
 2   quantity    7 non-null      object
 3   Totalprice  6 non-null      float64
dtypes: float64(2), object(2)
memory usage: 352.0+ bytes

In [ ]:
# Cleaning
#  1. wrong data
#  2. empty cells (remove and replace)
#  3.duplicates
#  4.wrong format

In [60]:
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [61]:
df3

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
3  A4 paper     NaN       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5         NaN
6     light   500.0       10       500.0

In [62]:
df3.dropna()

    items   cost quantity  Totalprice
0     pen   10.0       10       100.0
1  pencil   20.0       34       680.0
2    book   50.0       50      1000.0
4     toy   30.0       16       480.0
6   light  500.0       10       500.0

In [63]:
df3

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
3  A4 paper     NaN       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5         NaN
6     light   500.0       10       500.0

In [64]:
df4=df3.dropna() #original will not change

In [65]:
df4

    items   cost quantity  Totalprice
0     pen   10.0       10       100.0
1  pencil   20.0       34       680.0
2    book   50.0       50      1000.0
4     toy   30.0       16       480.0
6   light  500.0       10       500.0

In [66]:
df3

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
3  A4 paper     NaN       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5         NaN
6     light   500.0       10       500.0

In [67]:
df3.dropna(inplace=True)  #original will change

In [68]:
df3

    items   cost quantity  Totalprice
0     pen   10.0       10       100.0
1  pencil   20.0       34       680.0
2    book   50.0       50      1000.0
4     toy   30.0       16       480.0
6   light  500.0       10       500.0

In [69]:
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [70]:
temp= pd.concat([df3,df2])

In [71]:
temp

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
4       toy    30.0       16       480.0
6     light   500.0       10       500.0
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       20      1000.0
3  A4 paper    60.0       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5     10000.0
6     light   500.0        1       500.0

In [72]:
temp.reset_index()

    index     items    cost quantity  Totalprice
0       0       pen    10.0       10       100.0
1       1    pencil    20.0       34       680.0
2       2      book    50.0       50      1000.0
3       4       toy    30.0       16       480.0
4       6     light   500.0       10       500.0
5       0       pen    10.0       10       100.0
6       1    pencil    20.0       34       680.0
7       2      book    50.0       20      1000.0
8       3  A4 paper    60.0       15       900.0
9       4       toy    30.0       16       480.0
10      5       fan  2000.0        5     10000.0
11      6     light   500.0        1       500.0

In [74]:
temp.reset_index(drop=True)

       items    cost quantity  Totalprice
0        pen    10.0       10       100.0
1     pencil    20.0       34       680.0
2       book    50.0       50      1000.0
3        toy    30.0       16       480.0
4      light   500.0       10       500.0
5        pen    10.0       10       100.0
6     pencil    20.0       34       680.0
7       book    50.0       20      1000.0
8   A4 paper    60.0       15       900.0
9        toy    30.0       16       480.0
10       fan  2000.0        5     10000.0
11     light   500.0        1       500.0

In [75]:
temp

      items    cost quantity  Totalprice
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       50      1000.0
4       toy    30.0       16       480.0
6     light   500.0       10       500.0
0       pen    10.0       10       100.0
1    pencil    20.0       34       680.0
2      book    50.0       20      1000.0
3  A4 paper    60.0       15       900.0
4       toy    30.0       16       480.0
5       fan  2000.0        5     10000.0
6     light   500.0        1       500.0

In [82]:
df2

      items  cost  quantity  Totalprice
0       pen    10        10         100
1    pencil    20        34         680
2      book    50        20        1000
3  A4 paper    60        15         900
4       toy    30        16         480
5       fan  2000         5       10000
6     light   500         1         500

In [83]:
df2.iloc[3,1]=np.nan

In [84]:
df2

      items    cost  quantity  Totalprice
0       pen    10.0        10         100
1    pencil    20.0        34         680
2      book    50.0        20        1000
3  A4 paper     NaN        15         900
4       toy    30.0        16         480
5       fan  2000.0         5       10000
6     light   500.0         1         500

In [85]:
#wrong data
df2.fillna('hi')

      items    cost  quantity  Totalprice
0       pen    10.0        10         100
1    pencil    20.0        34         680
2      book    50.0        20        1000
3  A4 paper      hi        15         900
4       toy    30.0        16         480
5       fan  2000.0         5       10000
6     light   500.0         1         500

In [6]:
df2

      items  cost  quantity
0       pen    10        10
1    pencil    20        34
2      book    50        20
3  A4 paper    60        15
4       toy    30        16
5       fan  2000         5
6     light   500         1

In [5]:
df2.shape

(7, 3)